---
title: "Lecture 14: Plotly & Dashboards"
author: "Andy Turner"
date: "2023-10-24"
output: html_document
---

```{r}
library(tidyverse)
library(plotly)
library(p8105.datasets)
```

Focus on NYC Airbnb data.

```{r}
data("nyc_airbnb")

nyc_airbnb =
  nyc_airbnb |> 
  mutate(stars= review_scores_location/ 2) |> 
  select(borough= neighbourhood_group, neighbourhood,stars, price,
         room_type, lat, long) |> 
  drop_na(stars) |> 
  filter(
    borough == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500
    )
```
`drop_na()` can drop anything with the variable that is NA. 

Scaterrplot!

```{r}
nyc_airbnb |> 
  mutate(text_label= str_c("Price: $", price, "\nRating: ", stars)) |>
 plot_ly(
    x = ~lat, y = ~long, color= ~price, text=~text_label,
    type= "scatter", mode= "markers", alpha= 0.5)
```
`str_c` = string combine
`str_c("Label for variable", variable name, "Label for variable", variable name))
\n = new line

Let's do BOX PLOT

```{r}
nyc_airbnb |> 
  plot_ly(y = ~price, color = ~neighbourhood, type = "box", colors = "viridis")

nyc_airbnb |> 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) |> 
  plot_ly(y = ~price, color = ~neighbourhood, type = "box", colors = "viridis")
```

BAR PLOT
```{r}
nyc_airbnb |> 
  count(neighbourhood) |> 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) |>
  plot_ly(
  x = ~neighbourhood, y= ~n, color= ~neighbourhood, type= "bar", colors= "viridis")
```

# ggplotly

ggplot scatterplot

```{r}
ggp_scatter=
  nyc_airbnb |> 
  ggplot(aes(x= lat, y=long, color= price))+
  geom_point(alpha= .5)

```

